### ISSUE TITLE
Maven build/config issue

### ISSUE THREAD

**Issue by jamo3** [spring-guides/gs-accessing-data-gemfire#5]
Downloaded project through STS "Importing getting started content" and get error:

Missing artifact com.gemstone.gemfire:gemfire:jar:7.0.2

Also tried cloning repo with Git, same error.  Was not able to resolve this artifact with:
<dependency>
  <groupId>com.gemstone.gemfire</groupId>
  <artifactId>gemfire</artifactId>
  <version>7.0.2</version>
</dependency>

or find the artifact (any version) in nexus

**Comment by gregturn** [comment]
Check the build file. Latest has repo.spring.io libs-release they resolves to https://repo.spring.io/libs-release/com/gemstone/gemfire/gemfire/7.0.2/

**Comment by gregturn** [comment]
That was taken out in an earlier version of the guide, but fixed later. Master branch of the guide has it.
